### PR TITLE
Change "CFCRJ" to "CFCFRJ"

### LINKED ISSUE #13: Acronym error
Acronym error: "CFCRF" instead of "CFCRJ" in README.md, Section 2 (Overview) -> Problem Statement -> Item 2

### PR DESCRIPTION
**Pull request by jazcap53**
Fixes typo in README.md Section 2. Overview -> Problem Statement, item 2

### CODE REVIEW

**Comment by krook** [comment]
Good catch @jazcap53! Can you please push another commit to update the acronym to "CFCFRJ"? Just like the "for" in CFC, we include the "for" in CFCFRJ.

**Comment by jazcap53** [comment]
@krook Sure. The new push will conflict with the title of Diagram 1, though.

**Comment by krook** [comment]
Thanks @jazcap53. We'll need to update the image too. But this change should at least be correct if we change it now.

**Comment by jazcap53** [comment]
Thanks @krook. Will do!

**Review by krook — APPROVED** [review]

**Pull request merged**
